// import '/shelter/src/main/sass/main.scss'; 
import '/shelter/src/sass/main.scss'; 
import '/shelter/src/sass/footer.scss'; 
import '/shelter/src/sass/footer768.scss'; 
import '/shelter/src/sass/normalize.scss'; 
import '/shelter/src/sass/width1280.scss'; 
import '/shelter/src/sass/width768.scss'; 
import '/shelter/src/sass/width320.scss'; 
console.log('hi Main');
const pets = require('../pets/pets');